language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=firstrunwizard
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/


before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ app:enable firstrunwizard

before_script:
  - cd apps/$APP_NAME/

script:
  - cd tests
  - phpunit --configuration phpunit.xml

matrix:
  fast_finish: true
